[phases.setup]
nixPkgs = ["nodejs_20", "python310", "python310Packages.pip", "python310Packages.virtualenv"]

[phases.install]
cmds = [
  "pnpm install",
  "python -m venv --system-site-packages /opt/venv",
  "/opt/venv/bin/pip install -r pizzaz_server_python/requirements.txt"
]

[phases.build]
cmds = ["BASE_URL=https://openai-apps-sdk-examples-production-5f32.up.railway.app pnpm run build"]

[start]
cmd = "pnpm run serve & /opt/venv/bin/uvicorn pizzaz_server_python.main:app --host 0.0.0.0 --port $PORT"
